### ISSUE TITLE
Usable in a browser?

### ISSUE THREAD

**Issue by moxious** [Loupi/node-cypher-parser#11]
This is a great module I'd like to use.  As far as I can tell, this probably isn't usable in a browser because it depends on external compiled binaries, and those via node-gyp can't be used in a browser.  When I try to use it, I get the error:

```
./node_modules/cypher-parser/node_modules/node-pre-gyp/lib/info.js
Module not found: Can't resolve 'aws-sdk' in '(...)/node_modules/cypher-parser/node_modules/node-pre-gyp/lib'
```

This seems like a red herring error in that aws-sdk isn't needed and isn't related to cypher parsing, but digging deeper it appears that since the library isn't pure JS it probably won't work in a browser.

Is this correct or incorrect?

**Comment by bealoui1** [comment]
This is correct. The parser relies on a C module called libcypher-parser. And there is no WebAssembly build of that module available at that time.
