### ISSUE TITLE
regex operator bug due to outdated libcypher-parser

### ISSUE THREAD

**Issue by tungv** [Loupi/node-cypher-parser#12]
Hi Loupi,
libcypher-parser has released a fix for this bug. Can you help release node-cypher-parser with the latest binary (v0.6.2)?

Ref: https://github.com/cleishm/libcypher-parser/issues/9

**Comment by Loupi** [comment]
Hello Tungv,

Yes, there will be a new node-cypher-parser release in the coming days.

**Comment by tungv** [comment]
Great! Thank you so much
