### ISSUE TITLE
Support for Carbon MacBook (ARM64)

### ISSUE THREAD

**Issue by sylvainsf** [Loupi/node-cypher-parser#33]
I've already made it work locally, it just requires this change to package.json:
  "cpu": [
     "x64",
     "arm64"
   ]

And uploading the arm64 binary to your S3 bucket. As there's no way to include the binary in a PR I thought I'd open this issue instead. I've checked in the binary to my fork, so you can download it there if you like.

**Comment by sylvainsf** [comment]
arm64/cypher.node

**Comment by danielgerlag** [comment]
@Loupi ^
