### ISSUE TITLE
No support for CREATE?

### ISSUE THREAD

**Issue by Izhaki** [Loupi/node-cypher-parser#5]
const cypher = require('cypher-parser');

    const query = `CREATE (x) RETURN x`;

    const result = await cypher.parse({
      query,
      dumpAst: true,
      colorize: true,
      rawJson: true,
    });

results in:

```
Assertion failed: (cypher_astnode_instanceof(astnode, CYPHER_AST_MERGE)), function cypher_ast_merge_get_pattern_path, file ast_merge.c, line 82.
error Command failed with signal "SIGABRT".
```

**Comment by Loupi** [comment]
Fixed in https://github.com/Loupi/node-cypher-parser/releases/tag/0.1.2
