### ISSUE TITLE
Variable length relationships parse error

### ISSUE THREAD

**Issue by junknown** [Loupi/node-cypher-parser#9]
Hi,
another issue i found is that in roots i have no indication about relationships length range.
For example:

MATCH (actor)-[:TEST*1..3]-(movie)
    RETURN movie.title

gives to me this roots object without ***1..3** information :

>  [ { type: 'statement',
>     body:
>      { type: 'query',
>        clauses:
>         [ { type: 'match',
>             optional: false,
>             pattern:
>              { type: 'pattern',
>                paths:
>                 [ { type: 'pattern-path',
>                     elements:
>                      [ { type: 'node-pattern',
>                          identifier: { type: 'identifier', name: 'actor' },
>                          labels: [] },
**>                        { type: 'rel-pattern',
>                          direction: 2,
>                          reltypes: [ { type: 'reltype', name: 'TEST' } ] },**
>                        { type: 'node-pattern',
>                          identifier: { type: 'identifier', name: 'movie' },
>                          labels: [] } ] } ] },
>             hints: [] },
>           { type: 'return',
>             distinct: false,
>             includeExisting: false,
>             projections:
>              [ { type: 'projection',
>                  expression:
>                   { type: 'property-operator',
>                     expression: { type: 'identifier', name: 'movie' },
>                     propName: { type: 'prop-name', value: 'title' } },
>                  alias: { type: 'identifier', name: 'movie.title' } } ] } ],
>        options: [] },
>     options: [] } ]
>

**Comment by junknown** [comment]
I think the problem is here:

parser.cpp :1190

  Node("properties", cypher_ast_rel_pattern_get_properties);
  Node("varLength", cypher_ast_rel_pattern_get_properties);

maybe a typo, cypher_ast_rel_pattern_get_properties i think is wrong

**Comment by Loupi** [comment]
Thank you for the contribution, I'm going to release 0.1.3 today with this fix.

**Comment by Loupi** [comment]
Fixed in https://github.com/Loupi/node-cypher-parser/releases/tag/0.1.3
